version: "3"

services:
    api:
        build:
            dockerfile: Dockerfile.prod
        restart: always
        environment:
            - NODE_ENV=production

    postgres-db:
        restart: always
