version: "3"

services:
    api:
        build:
            dockerfile: Dockerfile.dev
        env_file:
            - ./packages/api/.env
        environment:
            - NODE_ENV=development
        volumes:
            - ./packages/api/src:/usr/app/src

    postgres-db:
        env_file:
            - ./packages/api/.env
