version: "3"

services:
    api:
        image: ch/api:latest
        container_name: ch-api
        build:
            context: ./packages/api
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        depends_on:
            - postgres-db

    postgres-db:
        image: postgres:latest
        container_name: ch-psql
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
