version: "3"

services:
    api:
        build:
            dockerfile: Dockerfile.prod
        env_file:
            - ./packages/api/.env.production
        restart: always
        environment:
            - NODE_ENV=production

    postgres-db:
        env_file:
            - ./packages/api/.env.production
        restart: always
